/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Reserva service. Represents a row in the &quot;BOOKINGS_Reserva&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.model.impl.ReservaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.model.impl.ReservaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Reserva
 * @generated
 */
@ProviderType
public interface ReservaModel
	extends BaseModel<Reserva>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a reserva model instance should use the {@link Reserva} interface instead.
	 */

	/**
	 * Returns the primary key of this reserva.
	 *
	 * @return the primary key of this reserva
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this reserva.
	 *
	 * @param primaryKey the primary key of this reserva
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this reserva.
	 *
	 * @return the uuid of this reserva
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this reserva.
	 *
	 * @param uuid the uuid of this reserva
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the id reserva of this reserva.
	 *
	 * @return the id reserva of this reserva
	 */
	public long getIdReserva();

	/**
	 * Sets the id reserva of this reserva.
	 *
	 * @param idReserva the id reserva of this reserva
	 */
	public void setIdReserva(long idReserva);

	/**
	 * Returns the group ID of this reserva.
	 *
	 * @return the group ID of this reserva
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this reserva.
	 *
	 * @param groupId the group ID of this reserva
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this reserva.
	 *
	 * @return the company ID of this reserva
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this reserva.
	 *
	 * @param companyId the company ID of this reserva
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this reserva.
	 *
	 * @return the user ID of this reserva
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this reserva.
	 *
	 * @param userId the user ID of this reserva
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this reserva.
	 *
	 * @return the user uuid of this reserva
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this reserva.
	 *
	 * @param userUuid the user uuid of this reserva
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this reserva.
	 *
	 * @return the user name of this reserva
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this reserva.
	 *
	 * @param userName the user name of this reserva
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this reserva.
	 *
	 * @return the create date of this reserva
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this reserva.
	 *
	 * @param createDate the create date of this reserva
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this reserva.
	 *
	 * @return the modified date of this reserva
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this reserva.
	 *
	 * @param modifiedDate the modified date of this reserva
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nombre of this reserva.
	 *
	 * @return the nombre of this reserva
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this reserva.
	 *
	 * @param nombre the nombre of this reserva
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the apellidos of this reserva.
	 *
	 * @return the apellidos of this reserva
	 */
	@AutoEscape
	public String getApellidos();

	/**
	 * Sets the apellidos of this reserva.
	 *
	 * @param apellidos the apellidos of this reserva
	 */
	public void setApellidos(String apellidos);

	/**
	 * Returns the email of this reserva.
	 *
	 * @return the email of this reserva
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this reserva.
	 *
	 * @param email the email of this reserva
	 */
	public void setEmail(String email);

	/**
	 * Returns the id alojamiento of this reserva.
	 *
	 * @return the id alojamiento of this reserva
	 */
	public long getIdAlojamiento();

	/**
	 * Sets the id alojamiento of this reserva.
	 *
	 * @param idAlojamiento the id alojamiento of this reserva
	 */
	public void setIdAlojamiento(long idAlojamiento);

	/**
	 * Returns the fecha entrada of this reserva.
	 *
	 * @return the fecha entrada of this reserva
	 */
	public Date getFechaEntrada();

	/**
	 * Sets the fecha entrada of this reserva.
	 *
	 * @param fechaEntrada the fecha entrada of this reserva
	 */
	public void setFechaEntrada(Date fechaEntrada);

	/**
	 * Returns the fecha salida of this reserva.
	 *
	 * @return the fecha salida of this reserva
	 */
	public Date getFechaSalida();

	/**
	 * Sets the fecha salida of this reserva.
	 *
	 * @param fechaSalida the fecha salida of this reserva
	 */
	public void setFechaSalida(Date fechaSalida);

	/**
	 * Returns the habitaciones of this reserva.
	 *
	 * @return the habitaciones of this reserva
	 */
	public int getHabitaciones();

	/**
	 * Sets the habitaciones of this reserva.
	 *
	 * @param habitaciones the habitaciones of this reserva
	 */
	public void setHabitaciones(int habitaciones);

	/**
	 * Returns the personas of this reserva.
	 *
	 * @return the personas of this reserva
	 */
	public int getPersonas();

	/**
	 * Sets the personas of this reserva.
	 *
	 * @param personas the personas of this reserva
	 */
	public void setPersonas(int personas);

	@Override
	public Reserva cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}